### ISSUE TITLE
Advertise

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/game-discount-checker#10]
## TODO

- [ ] Write posts in a couple subreddits
  - [ ] [r/CLI](https://www.reddit.com/r/CLI/)
  - [ ] [r/commandline](https://www.reddit.com/r/commandline/)
  - [ ] [r/terminal_porn](https://www.reddit.com/r/terminal_porn/)
