### ISSUE TITLE
Implement caching

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/game-discount-checker#12]
## Description

**Add it for `gog.js`'s `gameID` and other `/store_module` files?**

After first run / saving config with new GOG URL save gameID until URL is changed.

Check for faster method (<https://www.quora.com/How-is-SQLite-faster-than-writing-to-a-normal-file> ; <https://healeycodes.com/saving-data-in-javascript-without-a-database>):
- [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3)
- saving to file (fs) <- seems to be faster

**Comment by ErykDarnowski** [comment]
# Benchmarks:

## Setup:
- Linux Fedora VM (6 cores 12GB RAM)
- Performed creation of db, reading and deletion

## Results:

![benchmarks](https://user-images.githubusercontent.com/81530705/163853551-79301b1b-6b84-400c-a0e9-38c7a9543db8.png)

**Comment by ErykDarnowski** [comment]
## TODO
- [ ] benchmark speeds
- [ ] optimize JSON structure
- [ ] optimize updating values
- [ ] add cache implementation to:
    - [ ]  epic.js
    - [ ]  steam.js
    - [ ]  microsoft.js

**Comment by ErykDarnowski** [comment]
# Benchmarks:

## Setup:
- Linux Fedora VM (6 cores 12GB RAM)
- no EPIC request
- Performed:
    - noCache = no cache (getting data with puppeteer)
    - firstRun = getting data with puppeteer and creating cache.json file
    - secondRun = getting data from cache.json file

## Results:

![benchmarks](https://user-images.githubusercontent.com/81530705/164052144-dab0e99a-dcd1-406b-b357-75a05974c746.png)
