### ISSUE TITLE
Implement different region support

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/game-discount-checker#2]
## TODO

- [ ] Don't relly on `zł` in `epic.js`'s XPath
- [ ] Get currency / formatting of it from APIs
- [ ] See how websites take care of price formatting
- [ ] See what countries are supported by the stores
- [ ] Don't specify currency (format only based on numbers)
