### ISSUE TITLE
Finish up `README.md`

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/game-discount-checker#3]
## TODO

- [ ] Finish instructions
- [ ] Add badges <https://shields.io>
- [ ] Add <asciinema.org> animation as showcase
- [ ] Add info about the hyperfine benchmark:
```text
`hyperfine -i --prepare --warmup 3 'node app.js'` (With 1 Gigabit wired connection and cached GOG appID it achieves a ... time)
```
