### ISSUE TITLE
Improve performance (loading speed)

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/game-discount-checker#4]
## TODO

- [X] Asynchronous API requests
- [X] Improve epic.js request speed
- [ ] [Open multiple browsers at once instead of one for every store?](https://www.tabnine.com/code/javascript/functions/jest/setTimeout?snippet=5f6730c64b42a09e186777c0)
- [ ] Find API for Epic:
  - <https://github.com/SD4RK/epicstore_api>
  - <https://github.com/Anth3995/EpicGamesApi>
  - <https://github.com/AchetaGames/egs-api-rs>
  - <https://github.com/AuroPick/epic-free-games>
  - <https://github.com/HurricaneInteractive/epic-games-scraper>
