### ISSUE TITLE
Improve look of the output (prices table)

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/game-discount-checker#9]
## TODO

- [ ] Figure out nicer aligns
- [ ] Highlight lower prices / discounts (coloring / style)
- [ ] As default display table in basic ASCII (auto detect fonts)?
- [ ] Add cowsay mode somwhow / to just how much you can save msg?
- [ ] Check out other pkgs for printing tables [easy-table](https://www.npmjs.com/package/easy-table) ; [cli-table](https://github.com/Automattic/cli-table) ; [console-table](https://github.com/LvChengbin/console-table)
- [ ] Redraw table as new prices are being loaded instead instead of waiting for them?
- [ ] Add comparison column to table? (displays how % less is price compared to row above)
